name = Ofen Page
description = Ofen Page Layout
preview = preview.png
template = page-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar]        = Sidebar

regions[postscript]     = Postscript
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/page/page.layout.css



