name = Ofen Page
description = Ofen Page Layout
preview = preview.png
template = page-layout

; Regions
regions[header]         = Header
regions[branding]       = Branding
regions[login]          = Login
regions[top_menu]       = Top Menu
regions[language]       = Language Switch
regions[search]         = Search Box
regions[main_menu]      = Main Menu
regions[navigation]      = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar

regions[postscript]     = Postscript
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/page/page.layout.css
stylesheets[all][] = css/layouts/page/page.layout.no-query.css


