name = Forschungsatlas
description = Custom layout für die Seite mit dem Forschungsatlas
preview = preview.png
template = atlas-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[header_first]   = Header First
regions[header_second]  = Header Second
regions[navigation]     = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content

regions[footer]         = Footer
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth

; Stylesheets
stylesheets[all][] = css/layouts/atlas/atlas.layout.css
stylesheets[print][] = css/ofen.print.css
