name = Forschungsatlas
description = Custom layout für die Seite mit dem Forschungsatlas
preview = preview.png
template = atlas-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content

regions[featured]       = Featured
regions[atlas]          = Forschungsatlas
regions[news]           = Nachrichten
regions[products]       = Aktuelle Nefo Produkte
regions[misc]           = Events and News
regions[studies]        = Studies

regions[footer]         = Footer
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth

; Stylesheets
stylesheets[all][] = css/layouts/frontpage/atlas.layout.css


