name = Forscherprofile
description = layout für Forscherprofile
preview = preview.png
template = researcher-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar]        = Sidebar

regions[footer]         = Footer
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth


; Stylesheets
stylesheets[all][] = css/layouts/researcher/researcher.layout.css

; Scripts
scripts[] = js/ofen_researcher.behaviors.js



