name = Ofen Frontpage
description = Ofen Frontpage mobile first with 1 column layout.
preview = preview.png
template = frontpage-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[header_first]   = Header First
regions[header_second]  = Header Second
regions[navigation]     = Navigation

regions[highlighted]    = Highlighted
regions[help]           = Help
;regions[content]        = Content

regions[featured]       = Featured
regions[slider]         = Slider
regions[atlas]          = Forschungsatlas
regions[news]           = Nachrichten
regions[products]       = Aktuelle Nefo Produkte
regions[misc]           = Events and News
regions[studies]        = Studien
regions[sidebar]        = Sidebar
regions[interviews]     = Interviews

regions[footer]         = Footer
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth
regions[footer_fifth]   = Footer Fifth
regions[footer_sixth]   = Footer Sixth

; Stylesheets
stylesheets[all][] = css/layouts/frontpage/frontpage.layout.css
stylesheets[print][] = css/ofen.print.css

